server:
  port: 8081
spring:
  application:
    name: eureka-server-peer1
eureka:
  server:
    #自我保护模式true，表示没有接收到客户端的心跳，但也不会移除任何client
    enable-self-preservation: false
    #扫描失效服务的间隔时间
    eviction-interval-timer-in-ms: 60000
  client:
    # 是否将自己作为客户端注册到注册中心
    register-with-eureka: true
    # 是否从注册中心获取注册信息
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-peer2:8084/eureka/



